commented;modifiers;parameterAmount;loc;comment;code
false;public;0;4;;@Test public void testInstanceOfCancelTaskException() throws Exception {     assertTrue(CancelTaskException.class.isAssignableFrom(ProducerFailedException.class)). }
false;public;0;9;;@Test public void testCauseIsSerialized() throws Exception {     // Tests that the cause is stringified, because it might be an instance     // of a user level Exception, which can not be deserialized by the     // remote receiver's system class loader.     ProducerFailedException e = new ProducerFailedException(new Exception()).     assertNotNull(e.getCause()).     assertTrue(e.getCause() instanceof SerializedThrowable). }
